### ISSUE TITLE
Conectar app extraída con la API mediante capacitor (movil-estudiante)

### ISSUE THREAD

**Issue by gabrielp6** [TFGiando/classpip-movil-estudiante-dev#8]
Una vez tenemos Capacitor bien integrado en el componente, vamos a tratar de que se conecte correctamente con la API y podamos obtener respuestas haciendole las peticiones necesarias.

**Comment by DanielDCa** [comment]
Se habia pensado que era un bug, pero la aplicacion nativa (Android) hace bien las peticiones con la libreria de HTTPclient, es por eso que se aprovecho este ticket para eliminar basura que se habia dejado con el httpComunitty y algunas cosas mas
